language: php
os:
  - linux
  - windows

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - 'hhvm'
before_install:
  - printf "\n" | pecl install imagick
before_script: composer install
script: composer run-script test
